after :units do
  ### Americans
  allied_ht = Unit.find_by(name: "halftrack_allied")
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "riflemen"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "engineers"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "sniper_allied"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "30cal_hmg"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "mortar_allied"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "rangers"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "ambush_riflemen"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "spotter"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "officer_infantry"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "airborne"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "assault_airborne"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "airborne_hmg"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "airborne_mortar"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "airborne_sniper"))
  TransportAllowedUnit.create!(transport: allied_ht, allowed_unit: Unit.find_by(name: "mech_inf"))
  
  ### British
  universal_carrier = Unit.find_by(name: "universal_carrier")
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "infantry_section"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "recon_section"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "sappers"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "expert_sappers"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "lt"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "captain"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "canadian_section"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "ssf"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "commandos"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "piat_commandos"))
  TransportAllowedUnit.create!(transport: universal_carrier, allowed_unit: Unit.find_by(name: "polish_commandos"))

  kangaroo = Unit.find_by(name: "kangaroo")
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "infantry_section"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "recon_section"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "sappers"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "expert_sappers"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "lt"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "captain"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "canadian_section"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "ssf"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "commandos"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "piat_commandos"))
  TransportAllowedUnit.create!(transport: kangaroo, allowed_unit: Unit.find_by(name: "polish_commandos"))

  ## Commandos
  infantry_glider = Unit.find_by(name: "infantry_glider")
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "infantry_section"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "recon_section"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "sappers"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "expert_sappers"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "lt"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "captain"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "mortar_british"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "vickers_hmg"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "canadian_section"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "ssf"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "commandos"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "piat_commandos"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "polish_commandos"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "commando_hmg"))
  TransportAllowedUnit.create!(transport: infantry_glider, allowed_unit: Unit.find_by(name: "commando_mortar"))
  
  armor_glider = Unit.find_by(name: "armor_glider")
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "infantry_section"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "recon_section"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "sappers"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "expert_sappers"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "lt"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "captain"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "mortar_british"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "vickers_hmg"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "canadian_section"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "ssf"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "commandos"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "piat_commandos"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "polish_commandos"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "commando_hmg"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "commando_mortar"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "commando_2pdr"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "universal_carrier"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "bren_carrier"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "sas_jeep"))
  TransportAllowedUnit.create!(transport: armor_glider, allowed_unit: Unit.find_by(name: "tetrarch"))


  ### Wehr
  halftrack_axis = Unit.find_by(name: "halftrack_axis")
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "volksgrenadiers"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "grenadiers"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "pioneers"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "kch"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "medic"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "mg42"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "mortar_axis"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "sniper_axis"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "fortress_pioneers"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "officer_def"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "stormtroopers"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "flammentrupp"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "panzer_ace"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "sturmpioneers"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "saboteurs"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "officer_terror"))
  TransportAllowedUnit.create!(transport: halftrack_axis, allowed_unit: Unit.find_by(name: "mortar_terror"))

  ## Blitz
  panzer_ace = Unit.find_by(name: "panzer_ace")
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "puma_blitz"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "ostwind_blitz"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "geschutzwagen_blitz"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "stug_blitz"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "p4_blitz"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "panther_blitz"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "stuh"), allowed_unit: panzer_ace)
  TransportAllowedUnit.create!(transport: Unit.find_by(name: "tiger"), allowed_unit: panzer_ace)

  ### PE
  infantry_halftrack = Unit.find_by(name: "infantry_halftrack")
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "panzer_grenadiers"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "assault_grenadiers"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "tank_busters"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "ostfront_veterans"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "falls"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "gebirgs"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "luft_infantry"))
  TransportAllowedUnit.create!(transport: infantry_halftrack, allowed_unit: Unit.find_by(name: "crete_vets"))
end
